export class Geo {
  static location = [
    {id: 0, matches: 1, city: "Dortmund", url: "/img/geo/DAF-Bahnhofsvorplatz-1.jpg"},
    {id: 1, matches: 0, city: "Dortmund", url: "/img/geo/DAF-Bahnhofsvorplatz-2.jpg"},
    {id: 2, matches: 3, city: "Dortmund", url: "/img/geo/DAF-Corsopassage-1.jpg"},
    {id: 3, matches: 2, city: "Dortmund", url: "/img/geo/DAF-Corsopassage-2.jpg"},
    {id: 4, matches: 5, city: "Dortmund", url: "/img/geo/DAF-Dortberghaus-1.jpg"},
    {id: 5, matches: 4, city: "Dortmund", url: "/img/geo/DAF-Dortberghaus-2.jpg"},
    {id: 6, matches: 7, city: "Dortmund", url: "/img/geo/DAF-Hansaplatz-Arkaden-2a.jpg"},
    {id: 7, matches: 6, city: "Dortmund", url: "/img/geo/DAF-Hansaplatz-Arkaden-2b.jpg"},
    {id: 8, matches: 9, city: "Dortmund", url: "/img/geo/DAF-Hauptbahnhof-1.jpg"},
    {id: 9, matches: 8, city: "Dortmund", url: "/img/geo/DAF-Hauptbahnhof-2.jpg"},
    {id: 10, matches: 11, city: "Dortmund", url: "/img/geo/DAF-Karstadt-Sport.jpg"},
    {id: 11, matches: 10, city: "Dortmund", url: "/img/geo/DAF-Karstadt-Sporthaus-2.jpg"},
    {id: 12, matches: 13, city: "Dortmund", url: "/img/geo/DAF-Körnerplatz(Westentor)-1.jpg"},
    {id: 13, matches: 12, city: "Dortmund", url: "/img/geo/DAF-Körnerplatz(Westentor)-2.jpg"},
    {id: 14, matches: 15, city: "Dortmund", url: "/img/geo/DAF-Ostwallmuseum(Oberbergamt)-1.jpg"},
    {id: 15, matches: 14, city: "Dortmund", url: "/img/geo/DAF-Ostwallmuseum(Oberbergamt)-2.jpg"},
    {id: 16, matches: 17, city: "Dortmund", url: "/img/geo/DAF-Propsteikirche-1.jpg"},
    {id: 17, matches: 16, city: "Dortmund", url: "/img/geo/DAF-Propsteikriche-2.jpg"},
    {id: 18, matches: 19, city: "Dortmund", url: "/img/geo/DAF-Reinoldikirche-1.jpg"},
    {id: 19, matches: 18, city: "Dortmund", url: "/img/geo/DAF-Reinoldikirche-2.jpg"},
    {id: 20, matches: 21, city: "Dortmund", url: "/img/geo/DAF-Stadtthaus-1.jpg"},
    {id: 21, matches: 20, city: "Dortmund", url: "/img/geo/DAF-Stadthaus-2.jpg"},
    {id: 22, matches: 23, city: "Dortmund", url: "/img/geo/DAF-Stadttheater-1.jpg"},
    {id: 23, matches: 22, city: "Dortmund", url: "/img/geo/DAF-Stadttheater-2.jpg"},
    {id: 24, matches: 25, city: "Dortmund", url: "/img/geo/DAF-Stahlhaus(Löwenhof)-1.jpg"},
    {id: 25, matches: 24, city: "Dortmund", url: "/img/geo/DAF-Stahlhaus(Löwenhof)-2.jpg"},
    {id: 26, matches: 27, city: "Dortmund", url: "/img/geo/DAF-Synagoge(Platz-der-Synagoge)-1.jpg"},
    {id: 27, matches: 26, city: "Dortmund", url: "/img/geo/DAF-Synagoge(Platz-der-Synagoge)-2.jpg"},
  ]
}
